bazelbuild/bazel-blog

- _posts/2017-07-20-backward-compatibility.md
> Blog post about backward compatibility

- _posts/2017-08-25-introducing-sandboxfs.md
Please review this new blog post!
I'd like to make this go live on Friday, so please don't merge it yet.
> Blog post to announce sandboxfs

- BUILD
- README.md
- _posts/2017-10-16-windows-retrospect.md
- scripts/BUILD
- scripts/Dockerfile
- scripts/cloudbuild.yaml
- scripts/jekyll.bzl
- scripts/jekyll_build.sh.tpl
This adds both Bazel command to deploy and a Google cloud container builder config file.
Each commit are consistent so feel free to review commit by commit.
> Add automatic push to the blog

- _posts/2017-12-11-thanks-bazelcon2017.md
> fixed bullet format

- _posts/2017-02-27-protocol-buffers.md
: https://github.com/cgrushko/proto_library/
> Update protobuf blog to match new content in example repo

- _posts/2018-02-14-how-android-builds-work-in-bazel.md
- Blaze -> Bazel in title
- Add my name at the bottom
> Fix up blog posting

- _posts/2018-02-26-bazel-0.11.md
> Bazel 0.11 post

- _posts/2018-02-28-incremental-dexing.md
The list items are currently displayed inline, which is not easily readable.
> Fixed list formatting in incremental dexing post

- _posts/2018-04-11-bazel-0.12.md
Hopefully, it will be better (untested).
> Update blog post (formatting was partially broken).

- _config.yml
- _posts/2018-07-09-bazel-sync-and-resolved-file.md
...and freezing commits to obtain reproducible builds.
> Add a blog post about following git repositories

- _posts/2018-08-17-starlark.md
(the template cuts off all but the first paragraph behind a
click-to-expand)
> Formatting: merge first two paragraphs

- _posts/2018-08-30-bazelcon-is-coming.md
Hi! Can I get a review on this? I'd love to post by tomorrow (today if possible!). Thanks!
> Blog post about BazelCon 2018

- _posts/2015-07-01-Configuration-File.md
- _posts/2018-01-19-config-parsing-order.md
- _posts/2018-05-02-bazel-0.13.md
Also upgrades an old link from http to https.
> Fix links to bazelrc guide.

- _posts/2018-11-02_bazelcon-2018-recap.md
NOTE: Videos are not yet published on YouTube, but the direct links will work. Here's the sequence of publishing:
1) review this PR
2) activate the links on YT [davidstanke or dbjacobs can do this]
3) merge this PR
> Blog post: BazelCon 2018 Recap

- _posts/2018-12-05-multilanguage-build-system.md
Draft was reviewed by @dslomov, David, and @spomorski.
> Blog-post: Bazel - a multilanguage build system

- scripts/jekyll.bzl
Everything was fixed done with Buildifier, no manual change
Tested:
`bazel test //... --all_incompatible_changes`
> Fix for Bazel incompatible changes

- _posts/2019-05-01-bazel-0.25.md
Fixes https://github.com/bazelbuild/bazel-blog/issues/168
> Escape rules_foreign_cc

- _posts/2019-05-07-builds-without-bytes.md
> Address comments of "Faster remote builds in Bazel 0.25"

- _posts/2019-07-10-bazel-0.28.md
> Reinstate and elaborate note about aapt2 support in 0.28 blogpost

- _posts/2019-08-12-BuildMeetup-CallForSpeakers.md
> Add blog post about london meetup

- _posts/2019-09-29-intellij-bazel-sync.md
Some edit improvements to the IJwB post.
> Update IJwBazel blogpost - sentence structures, formatting, wording

- _posts/2016-03-31-autoconfiguration.md
> Fix broken doc links in `2016-03-31-autoconfiguration.md`

- _posts/2019-09-30-bazelcon-update.md
Remove pointers to obsolete forms from older blog post.
> update bazelcon pointers

- _config.yml
- _posts/2019-12-20-bazelcon-2019.md
> Add mnarinsky's blogpost for Bazelcon 2019

- _posts/2020-03-31-bazel-3.0.md
Will wait until release is ready to merge.
> Add release notes for Bazel 3.0 release.

- _posts/2019-07-10-bazel-0.28.md
> Fix --auto_output_filter link in 0.28 blogpost

- _posts/2018-08-22-bazel-homebrew.md
> Remove deprecated tap-pin instructions in Homebrew blogpost

- _includes/head.html
> Add Twitter card meta tag to <head>

- _posts/2020-11-11-json-workers.md
This has been reviewed by Lars, and Ran from docs.
> Create blog post introducing JSON workers

- _posts/2022-02-17-Launching-new-Bazel-site.md
GitHub seems to process the Markdown just fine, but Jekyll lets us down :(
> Attempt 2 at fixing the list formatting

- feed.xml
Also blog title should escape special characters  
Fixes #275
> xml_escape blog post title

- CODEOWNERS
Give better defaults for different slices.
> Add fwe@ and reorganize CODEOWNERS

- _posts/2023-07-24-whats-new-with-bzlmod.md
Our CSS doesn't work well with `<strong><a>...</a></strong>`, but `<a><strong>...</strong></a>` is fine.
> fix bold links in latest post

- _posts/2024-03-18-intellij-q2-2023-q1-2024-community-update.md
> IntelliJ Q2'23 - Q1'24 community update
