_posts/2017-04-21-JDK7-deprecation.md

Importing bazelbuild/bazel commit f596af6.

Add blog post announcing deprecation of the JDK7 installer.

---

_includes/footer.html

In a document comment, @sillsm said it was OK to have the copyright year showing the current date.
Instead of using a fixed date, I used the technique described at http://www.adamwadeharris.com/get-current-year-in-jekyll/
Same change as https://github.com/bazelbuild/bazel-website/pull/8

Make sure Copyright year is always up to date.

---

scripts/serve-docs.sh

* Send SIGKILL to previous Jekyll process rather than SIGTERM, which
does not kill the process on Linux.
* Return to original directory after running Jekyll command so that
rebuild command works.

Fixes to serve-docs script.

---

_posts/2015-04-06-Simplified-Workspace-Creation.md
_posts/2015-06-17-visualize-your-build.md
_posts/2015-07-01-Configuration-File.md
_posts/2015-07-28-docker_build.md
_posts/2015-09-01-beta-release.md
_posts/2016-01-27-continuous-integration.md
_posts/2016-02-23-0.2.0-release.md
_posts/2016-03-18-sandbox-easier-debug.md
_posts/2016-06-10-0.3.0-release.md
_posts/2016-06-10-ide-support.md
_posts/2016-11-04-bazel-build.md
_posts/2017-02-22-repository-invalidation.md
_posts/2017-02-27-protocol-buffers.md
_posts/2017-03-07-java-sandwich.md
_posts/2017-05-26-Bazel-0-5-0-release.md

I've gone through and updated links to docs.bazel.build and blog.bazel.build.
Closes #24

Fix broken doc and blog links

---

_posts/2017-02-27-protocol-buffers.md

Fix unescaped underscores in protobuffer blog post

---

_includes/header.html

Make the search post to https://bazel.build
Fixes #17

Fix search 404s

---

_posts/2017-09-27-release-cadence.md

Use term "backward incompatible" change rather than "breaking" change

Use term "backward incompatible" rather than "breaking"

---

_posts/2018-01-19-config-parsing-order.md

Hey Laszlo! Thanks for volunteering to help with the Bazel config announcement :)
This document is a mostly straightforward port of the internal version, with the short introduction added to replace the role of the email. I'm planning on waiting for the Bazel 0.10 release to post this, but it's ready for review now.

--config migration doc

---

_posts/2018-02-14-how-android-builds-work-in-bazel.md

Fix Jekyll: ClassNotFound: no lexer for alias 'build' found

---

feed.xml

This is breaking links in Slacks' RSS feed integration

Fix RSS feed base URL

---

_includes/blog-sidebar.html
archive.html

I realized that there isn't an easy way to find a certain post, so I made an archive page with help from [this tutorial](http://chris.house/blog/building-a-simple-archive-page-with-jekyll/).
It looks pretty simple:
I've also added a link to this page in the sidebar for easy access.

Create an archive page for blogposts

---

_layouts/posts.html

@spomorski sorry, commit eb623a1a660e93331d2543f10b1b5013fec0fb3c broke `bazel build //:site`. This fixes it because the archive page doesn't have a date, but uses the layout for posts.

Fixed compilation error for archive page because of lack of date

---

_posts/2018-04-13-preliminary-sandboxfs-support.md

This blog post briefly covers how sandboxing works in Bazel, presents
the preliminary performance results we have done gotten from using
sandboxfs, tells users how to use sandboxfs with Bazel, and outlines
what the next steps are.

Blog post to announce sandboxfs support in Bazel

---

_sass/style.scss
_sass/tables.scss
css/main.scss

Import the minimal amount of code from Bootstrap in order to render tables
nicely in posts, which is necessary by the latest post on sandboxfs.
This is a bit of a hack: we should instead be building Bootstrap from its
SASS sources and then using a small custom rule to inherit those rules into
the elements that need them... but this looks non-trivial.

Fix table rendering

---

_config.yml
archive.html

This PR sets the default `enable_comments` metadata for all posts to true, therefore enabling Disqus comments on the individual post page. It also sets the layout to `posts` by default.
The Archive page does not need comments, so I've disabled it.

Enable comments on all posts and disable comments on archive page

---

index.html

Our blog posts tend to be long... very long.  The previous blog index
page was showing the full posts, which made it completely unreadable.
It was impossible to quickly skim through the page looking for what
the newest posts are, as the post titles would be "clobbered" by all
the content.
This change makes the index page only show the post excerpts and adds
a little footer to each indicating how much longer they are and how
many comments they have.  This makes it trivial, at a quick glance,
to see what has recently been published.
This should also help the trends I have observed in which some people
hold onto posting a new entry because the new entry would eclipse
older content.

Make the blog's front page readable

---

_config.yml
_layouts/posts.html
index.html

The disqus comment feature appears to be not consistently enabled (looks like a problem with the publishing pipeline). Moreover, we're not sure it's really a useful feature. The bazel-discuss mailing list is where we like to talk.
Disabling comments pending further, um, discussion.

disable disqus comments

---

_posts/2018-09-14-bazel-0.17.md

The current phrasing sounds like our contributors work at Google.

Fixed phrasing for contributor attributions

---

_includes/blog-sidebar.html
_includes/head.html

Some apps, when given a link to a blog page, can discover the RSS feed automatically based on the presence of a `<link>` tag in the head or rel/type attributes on an `<a>` within the page. These commits add the necessary tag and attributes for this to work on the Bazel blog.
The value in the `title` attribute is what is typically presented to users, so may need to adjusted if 'Bazel Blog' is not desired.

Fix discovery of RSS feed

---

_config.yml

As discussed with @helenalt we were hoping to contribute a bazel blog post about the hackathon - I think my name needs to be here if I were to post it under my name; although I don't think there are any non-Googlers already.

Add Ed Baunton as bazel blog post author

---

_posts/2018-12-14-Bazel-0.20.0.md

It seems like the markdown parser for the blog posts treats any `_` as start of an italics block.
This PR fixes the formatting by wrapping all `_` withs code blocks.

Fix 0.20.0 announcement blog post markdown errors

---

_posts/2018-12-19-bazel-0.21.md

I think this change was important enough that it should have ended up in
the release notes. Unfortunately, I wasn't fully aware that this was
accomplished through 'Relnotes' tags in commit messages.

Document the change in HTTP_PROXY handling in Bazel 0.21.

---

_posts/2019-02-01-dynamic-spawn-scheduler.md

- Avoid implying that remote execution is problematic: we have picked
pathological cases for our measurements.
- Clarify that this feature is experimental.
- Warn users about potential correctness issues.
- Clarify that most measurements were taken against Google's internal
remote execution engine and that they are not indicative of RBE
performance.

Address feedback for the dynamic scheduler post

---

_posts/2019-07-10-bazel-0.28.md

Nothing has been changed on the Bazel side yet.

Remove note about aapt being deprecated in favour of aapt2.

---

scripts/cloudbuild.yaml

The GCS bucket uses bucket-level permissions now, so setting the ACL on individual files results in an error and is no longer needed.

cloudbuild.yaml: Remove failing and unneeded step

---

_includes/head.html

None of these domain patterns should ever hit blog.bazel.build -- remove redundant javascript redirect code

Remove js redirects

---

_posts/2017-09-27-release-cadence.md

By making it point to a more relevant and permanent page: the list of Bazel users.

Fix broken link

---

_posts/2017-02-27-protocol-buffers.md
_posts/2019-10-01-protobuf-updates.md

Fixes #188 
TODO before this can be merged:

Update protocol buffers blogpost for the deprecation of native Protobuf rules

---

_posts/2017-02-27-protocol-buffers.md

Update Protobuf post to reflect --incompatible_load_proto_toolchain_for_javalite_from_com_google_protobuf

---

_layouts/posts.html

This adds an automatic link for headers in blogposts.

Add AnchorJS to post headers

---

_posts/2020-05-27-bazel-3-2.md

Update Bazel 3.2 release notes to remove include scanning reference.

Update Bazel 3.2 release notes

---

_posts/2020-10-20-bazel-3-7.md

Preparing to release tomorrow.

Blog post for Bazel 3.7

---

_posts/2022-01-19-bazel-5.0.md

`--incompatible_restrict_string_escapes` was removed
[here](https://github.com/bazelbuild/bazel/commit/21b4b1a489c991682b9fcc9a10b468b9ea18e931)
cc @Wyverald 
see https://github.com/bazelbuild/bazel/pull/14695

fix: update 5.0 post with breaking change

---

_includes/header.html
search.html

The previous version used search.html from the Bazel website, which was deleted as part of the migration to the new site.
This commit adds this particular file to the repository.
Downside: The file contains links to the deprecated docs.bazel.build site.

Fix search box

---

_includes/blog-sidebar.html

Apparently FeedBurner has been in maintenance mode for quite some time now.
Fixes https://github.com/bazelbuild/bazel-blog/issues/289

Delete FeedBurner widget

---

scripts/jekyll_build.sh.tpl

This uses bash-only features (specifically I saw errors with the `function` declarations), so be honest that this wants bash.

Fix jekyll serve shebang

---

_posts/2022-11-15-build-performance-metrics.md

`--experimental_collect_worker_data_in_profiler` for collecting worker memory usage, not `--experimental_collect_system_network_usage`.

Fix incorrect flag in build performance blogpost
